cab/config/routes.rb
Rails.application.routes.draw do
  resources :cabsses
  resources :drivers

  

end

cab/app/models/cabss.rb
class Cabss < ActiveRecord::Base
end

cab/app/models/driver.rb
class Driver < ActiveRecord::Base
end

cab/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cab/app/controllers/cabsses_controller.rb
class CabssesController < ApplicationController
  before_action :set_cabss, only: [:show, :edit, :update, :destroy]

  # GET /cabsses
  # GET /cabsses.json
  def index
    @cabsses = Cabss.all
  end

  # GET /cabsses/1
  # GET /cabsses/1.json
  def show
  end

  # GET /cabsses/new
  def new
    @cabss = Cabss.new
  end

  # GET /cabsses/1/edit
  def edit
  end

  # POST /cabsses
  # POST /cabsses.json
  def create
    @cabss = Cabss.new(cabss_params)

    respond_to do |format|
      if @cabss.save
        format.html { redirect_to @cabss, notice: 'Cabss was successfully created.' }
        format.json { render :show, status: :created, location: @cabss }
      else
        format.html { render :new }
        format.json { render json: @cabss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabsses/1
  # PATCH/PUT /cabsses/1.json
  def update
    respond_to do |format|
      if @cabss.update(cabss_params)
        format.html { redirect_to @cabss, notice: 'Cabss was successfully updated.' }
        format.json { render :show, status: :ok, location: @cabss }
      else
        format.html { render :edit }
        format.json { render json: @cabss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabsses/1
  # DELETE /cabsses/1.json
  def destroy
    @cabss.destroy
    respond_to do |format|
      format.html { redirect_to cabsses_url, notice: 'Cabss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabss
      @cabss = Cabss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cabss_params
      params.require(:cabss).permit(:cab_type, :cab_no, :rate, :insure)
    end
end

cab/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /driveres
  # GET /driveres.json
  def index
    @drivers = Driver.all
  end

  # GET /driveres/1
  # GET /driveres/1.json
  def show
  end

  # GET /driveres/new
  def new
    @driver = Driver.new
  end

  # GET /driveres/1/edit
  def edit
  end

  # POST /driveres
  # POST /driveres.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /driveres/1
  # PATCH/PUT /driveres/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /driveres/1
  # DELETE /driveres/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to driveres_url, notice: 'driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:driver_name, :license_no, :experience_in_years)
    end
end

cab/app/helpers/application_helper.rb
module ApplicationHelper
end

cab/app/helpers/cabsses_helper.rb
module CabssesHelper
end

cab/app/views/cabsses/_form.html.erb
<%= form_for(@cabss) do |f| %>
  <% if @cabss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabss.errors.count, "error") %> prohibited this cabss from being saved:</h2>

      <ul>
      <% @cabss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cab_type %><br>
    <%= f.text_field :cab_type %>
  </div>
  <div class="field">
    <%= f.label :cab_no %><br>
    <%= f.text_field :cab_no %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="field">
    <%= f.label :insure %><br>
    <%= f.check_box :insure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cab/app/views/cabsses/edit.html.erb
<h1>Editing Cabss</h1>

<%= render 'form' %>

<%= link_to 'Show', @cabss %> |
<%= link_to 'Back', cabsses_path %>

cab/app/views/cabsses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cabsses</h1>

<table>
  <thead>
    <tr>
      <th>Cab type</th>
      <th>Cab no</th>
      <th>Rate</th>
      <th>Insure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabsses.each do |cabss| %>
      <tr>
        <td><%= cabss.cab_type %></td>
        <td><%= cabss.cab_no %></td>
        <td><%= cabss.rate %></td>
        <td><%= cabss.insure %></td>
        <td><%= link_to 'Show', cabss %></td>
        <td><%= link_to 'Edit', edit_cabss_path(cabss) %></td>
        <td><%= link_to 'Destroy', cabss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabss', new_cabss_path %>

cab/app/views/cabsses/new.html.erb
<h1>New Cabss</h1>

<%= render 'form' %>

<%= link_to 'Back', cabsses_path %>

cab/app/views/cabsses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cab type:</strong>
  <%= @cabss.cab_type %>
</p>

<p>
  <strong>Cab no:</strong>
  <%= @cabss.cab_no %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @cabss.rate %>
</p>

<p>
  <strong>Insure:</strong>
  <%= @cabss.insure %>
</p>

<%= link_to 'Edit', edit_cabss_path(@cabss) %> |
<%= link_to 'Back', cabsses_path %>

cab/app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Driver Name</th>
      <th>License no</th>
      <th>Experience_in_years</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.driver_name %></td>
        <td><%= driver.license_no %></td>
        <td><%= driver.experience_in_years %></td>
        
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drivers', new_driver_path %>

cab/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>